### ISSUE TITLE
ltr_finder exit with task undone

### ISSUE THREAD

**Issue by FlyPythons** [xzhub/LTR_Finder#2]
Hi: 
  when i run ltr_finder with cmd 'ltr_finder -a /home/usr/bin/ps_scan -t Hg17-tRNAs.fa -w 0 genome.fasta', the program exit with error "terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc".
  I find that may due to one of the contig in 'genome.fasta', this contig has a ~50 kb oligo "C" with some "A" like  "CCCCCCCCCACCCCCCCCCCACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCACCCC". 
  It may be a bug in ltr_finder or ps_scan?

**Comment by xzhub** [comment]
Could you please attach a test file for me to debug the code? Please make the file as small as possible.

**Comment by FlyPythons** [comment]
Thanks for your reply, the test file has been uploaded.
[test.txt](https://github.com/xzhub/LTR_Finder/files/1666341/test.txt)

**Comment by xzhub** [comment]
This does not look like a software bug, it's more like a memory issue. This particular sequence has many similar structures, therefore ltr_finder has difficulties to generate the results. My computer has 16GB memory, ltr_finder can never run through on this sequence, it always get killed by the system due to insufficient memories. 
Will work out some solutions so the ltr_finder can handle this type of sequence elegantly.

**Comment by xzhub** [comment]
I've forgot that I resolved this issue long time ago. Please use '-C' option: 

```
$ ./ltr_finder -a ps_scan -t latest_tRNA/hg19-tRNAs.fa -w 0 -C test/test.txt
Program    : LTR_FINDER
Version    : 1.07

Predict protein Domains 0.178 second
>Sequence: contig1 Len:50000
No LTR Retrotransposons Found

Total consume 0.417 second
```
