### ISSUE TITLE
Very slow when running on large and contiguous sequences

### ISSUE THREAD

**Issue by oushujun** [xzhub/LTR_Finder#3]
Hello,

Good to know LTR_Finder is on GitHub! 

I am using the output of LTR_Finder as one of the input sources to feed my program [LTR_retriever](https://github.com/oushujun/LTR_retriever). It was running very smoothly most of the time. However, when used on large and contiguous sequences such as wheat and maize genomes, LTR_Finder became very slow. For example, I have been running the current version (1.0.7) of LTR_Finder on chromosome 1 of the maize [CML247](https://www.ncbi.nlm.nih.gov/assembly/GCA_002682915.2) genome for weeks, but nothing was produced yet.

The parameters I used:
ltr_finder -C -D 15000 -d 1000 -L 7000 -l 100 -p 20 -M 0.9 Maize_CML247_v1.2_NGS_GCA_002682915.2.fa > out.scn &

This is somewhat similar to the old version of Tandem Repeat Finder (trf), which was also very slow on long and contiguous sequences. However, I noticed the trf program has several [updates](https://tandem.bu.edu/trf/trf.download.html) regarding the program compatibility to long centromeric regions. If you happen to incorporate trf or similar algorithms in your program, is it possible that you provide a quick fix and have LTR_Finder updated? If you didn't use trf in LTR_Finder, do you have any ideas to improve it regarding this problem?

Also, is it possible to add the parallel functionality to LTR_Finder?

Thank you very much for developing and maintaining LTR_Finder!

Regards,
Shujun

**Comment by xzhub** [comment]
For now, I would suggest you break the long chromosome sequence into several small fragments. It's safe to break at the Ns, since usually those Ns indicate long unknown bases. 
I am thinking of wrapping the LTR_Finder program into a script that breaks the long sequences automatically, I will break the sequences at 50 or more Ns. However, I don't know when I can have time to work on this yet.

**Comment by oushujun** [comment]
OK, thanks for your suggestions. Breaking the sequence based on gaps will change the coordinate system entirely tho.

**Comment by anandksrao** [comment]
Was this issue resolved?
I am using [oushujun's](https://github.com/oushujun) [LTR_retriever](https://github.com/oushujun/LTR_retriever), and one of the inputs is LTR_Finder results

Instead of splitting at Ns, I wonder if there can be some value to running LTR_Finder for each pseudomolecule in the genome assembly.

Since another open issue from Feb, 2019 is still unanswered, I am really hoping I will receive a response here. Thanks!

**Comment by oushujun** [comment]
@anandksrao It's kind of resolved by using a wrapper around it: https://github.com/oushujun/LTR_FINDER_parallel
