### ISSUE TITLE
Too many redundant results

### ISSUE THREAD

**Issue by li081766** [xzhub/LTR_Finder#5]
Hi:
when I run ltr_finder, the program generated too many redundant results.
Like:
Contig0_pilon   LTR_Finder   LTR	12559	14998	.	+	.	ID=Contig0_pilon_8_ltr;
Contig0_pilon	LTR_Finder	LTR	12568	15026	.	+	.	ID=Contig0_pilon_9_ltr;
Contig0_pilon	LTR_Finder	LTR	12568	15026	.	+	.	ID=Contig0_pilon_10_ltr;
Contig0_pilon	LTR_Finder	LTR	12568	15026	.	+	.	ID=Contig0_pilon_11_ltr;
Contig0_pilon	LTR_Finder	LTR	12568	15026	.	+	.	ID=Contig0_pilon_12_ltr;
Contig0_pilon	LTR_Finder	LTR	12568	15026	.	+	.	ID=Contig0_pilon_13_ltr;
Contig0_pilon	LTR_Finder	LTR	12568	15026	.	+	.	ID=Contig0_pilon_14_ltr;
Contig0_pilon	LTR_Finder	LTR	12568	23729	.	-	.	ID=Contig0_pilon_15_ltr;
Contig0_pilon	LTR_Finder	LTR	12568	32712	.	-	.	ID=Contig0_pilon_16_ltr;
Contig0_pilon	LTR_Finder	LTR	12570	32712	.	-	.	ID=Contig0_pilon_17_ltr;
Contig0_pilon	LTR_Finder	LTR	12570	32712	.	-	.	ID=Contig0_pilon_18_ltr;

How can I remove the redundancies?

Thank you very much for helping!

Jack

**Comment by xzhub** [comment]
Usually, by checking only the sequence structure itself, you will see quite a lot LTRs. However, if you take protein domains into account, the number of LTRs will decrease. Please try to add the "-a" option with ps_scan, so that LTR_Finder can get the protein domain information. Together with -S and -F options in argument, you should see less outputs.

**Comment by li081766** [comment]
Thanks. 
I will try again based on your suggestion
